CREATE TABLE contests (
   
    id VARCHAR(36) PRIMARY KEY,


    quiz_id VARCHAR(36) NOT NULL,
    creator_id VARCHAR(36) NOT NULL,

    title VARCHAR(255) NOT NULL,
    access_code VARCHAR(10) UNIQUE,


    status ENUM('SCHEDULED', 'ACTIVE', 'COMPLETED', 'CANCELLED') NOT NULL DEFAULT 'SCHEDULED',


    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);